### ISSUE TITLE
PEP-1

### ISSUE THREAD

**Issue by servilla** [PASTAplus/PEP#3]
Actions to be taken:
1. Reference schema.org under Proposed Solution and explain its (schema.org) role as related to this solution.
2. Note whether there are any alternative/competing solutions at the end of the Proposed Solution and state why the suggested solution is recommended.
3. Under Open Issues (Data Package Best Practices), describe if this solution is the best for the community and if SOSO has a trajectory to become an official standard for the community.
4. How do we address the immutable/mutable URI issue - e.g., DataONE most recent model?

**Comment by servilla** [comment]
[pep-1.pdf](https://github.com/user-attachments/files/16462245/pep-1.pdf)

**Comment by clnsmth** [comment]
@servilla I can't think of a good way to address the immutable/mutable URI issue. @rogerdahl do you have any ideas, specifically for the DataONE case?

**Comment by servilla** [comment]
> @servilla I can't think of a good way to address the immutable/mutable URI issue. @rogerdahl do you have any ideas, specifically for the DataONE case?

Perhaps it suffices that we never use a URI in an annotation that points to a mutable object, even if it means ignoring a DOI in favor of another style of PID. This way, the object being referenced would always be traceable through the PID (not the DOI) even if the DOI is transferred to reference the latest version of the object.

**Comment by clnsmth** [comment]
> Perhaps it suffices that we never use a URI in an annotation that points to a mutable object, even if it means ignoring a DOI in favor of another style of PID. This way, the object being referenced would always be traceable through the PID (not the DOI) even if the DOI is transferred to reference the latest version of the object.

This seems like a reasonable solution. I'll add it to the PEP.

**Comment by clnsmth** [comment]
The [data replication guidelines](https://edirepository.org/resources/defining-data-replication) and a related [news article](https://edirepository.org/news/news-20241009.00) have been published to the EDI website. Additionally, the data packaging best practices working group has been notified via [GitHub issue](https://github.com/EDIorg/data-package-best-practices/issues/88).
